### PR TITLE
Create publication tc

### PR DESCRIPTION
**Pull request by mayboroda1985**
Created test cases for Publication Create, added API publicationCreate

### CODE REVIEW

**Review by JuliaEde — COMMENTED** [review]
I did it

**Comment by JuliaEde** [comment]
LGTM

**Review by JuliaEde — DISMISSED** [review]
LGTM

**Review by JuliaEde — DISMISSED** [review]
LGTM

**Review by polina-atl — APPROVED** [review]
LGTM

**Pull request merged**
